AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 80

Rails:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
